openapi: 3.0.0
info:
  version: 1.0.0
  title: Roman Numerals API
  description: API docs for Roman Numerals API converter

servers:
  - url: http://localhost

paths:
  /:
    get:
      operationId: Default
      summary: The default route
      responses:
        '404':
          $ref: '#/components/responses/404'
  /v1/convert-integer-to-numeral:
    post:
      operationId: Convert integer to numeral
      summary: Take an integer and transform it to a roman numeral
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                integer:
                  type: integer
              example:
                integer: 123
      responses:
        '400':
          $ref: '#/components/responses/400'
        '422':
          $ref: '#/components/responses/422'
        '200':
          $ref: '#/components/responses/conversion-is-successful'

  /v1/statistics/most-popular:
    get:
      operationId: Most popular conversions
      summary: Get the statistics for the ten most popular conversions
      responses:
        '422':
          $ref: '#/components/responses/422'
        '200':
          $ref: '#/components/responses/most-popular'

  /v1/statistics/most-recent:
    get:
      operationId: Most recent conversions
      summary: Get the statistics for the ten most recent conversions
      responses:
        '422':
          $ref: '#/components/responses/422'
        '200':
          $ref: '#/components/responses/most-recent'

components:
  responses:
    201:
      description: The item is created
    200Empty:
      description: Empty OK response
    400:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    401:
      description: Unauthorized
    404:
      description: Not Found
    422:
      description: Unprocessable Entity
    conversion-is-successful:
      description: A conversion was successful between an integer and a roman numeral
      content:
        application/json:
          schema:
            title: A 200 OK response for a complete conversion
            type: object
            properties:
              integer:
                type: number
              numeral:
                type: string
              converted_at:
                type: string
            example:
              integer: 4
              numeral: 'IV'
              converted_at: '2024-03-03 12:12:12'
    most-recent:
      description: The response for the most recent look up
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                integer:
                  type: number
                numeral:
                  type: string
                converted_at:
                  type: string
              example:
                integer: 4
                numeral: 'IV'
                converted_at: '2024-03-03 12:12:12'
            example:
              - integer: 4
                numeral: 'IV'
                converted_at: '2024-03-03 12:12:12'
              - integer: 3
                numeral: 'III'
                converted_at: '2024-03-03 12:12:12'
    most-popular:
      description: The response for the most popular conversions
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                numeral:
                  type: string
                total_conversion_count:
                  type: number
              example:
                numeral: 'IV'
                total_conversion_count: 4
            example:
              - numeral: 'IV'
                total_conversion_count: 4
              - numeral: 'I'
                total_conversion_count: 2