name: "Standards"

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer, cs2pr

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
          mv phpcs.phar packages/roman-numerals-api
      - name: Detect coding standard violations
        run: cd ./packages/roman-numerals-api && php phpcs.phar --standard=ruleset.xml
